### ISSUE TITLE
Make it in agreement with the real es2016 definition

### ISSUE THREAD

**Issue by QuentinRoy** [ysmood/babel-preset-es2016#1]
This package does not seem to be in agreement with the real es2016 definition.

In my humble opinion, it should not include:
- react transform: not part of the ecma script specification whatsoever,
- babel runtime: should not be imposed by the preset but be the choice of the consumer,
- trailing commas in function: still in stage 3,
- object rest spread: still in stage 2,
- class properties: still in stage 1

However it should include:
- babel-plugin-syntax-exponentiation-operator

And that is all because if I am not mistaken and according to [this](http://www.2ality.com/2016/01/ecmascript-2016.html) and [this](https://twitter.com/bterlson/status/692427832555892736), ES2016 (to be announced next March the 1st) is likely to have only 2 features: the exponential syntax and Array.prototype.include (which should be part of the polyfill). 

[See here for the progress of the different proposals](https://github.com/tc39/ecma262).

**Comment by ysmood** [comment]
Thanks for your advice.
