### ISSUE TITLE
Transfer ownership to the babel repo

### ISSUE THREAD

**Issue by hzoo** [ysmood/babel-preset-es2016#2]
@ysmood Thanks for making this repo/preset for everyone to use! This is mainly a request for the [npm package](https://www.npmjs.com/package/babel-preset-es2016) but I was wondering if you would be cool with allowing babel to maintain and take over the preset given we have the `babel-preset-es2015` package and plan to do so for future years.

**Comment by ysmood** [comment]
It's my pleasure to do so, the interest of the whole community should be always put in the first place. I'd like to transfer both the github repo and the npm package to babel. But I want to confirm the two account names first. Or will it be ok if I transfer them to your account?

**Comment by hzoo** [comment]
Sure either is good (for github `babel` works).
I'm `hzoo` on npm https://www.npmjs.com/~hzoo (we don't have a babel npm org yet).

**Comment by ysmood** [comment]
Done. If you have any issue with the authorities please contact me.

**Comment by hzoo** [comment]
Awesome. Thanks for being understanding! Thinking about it now, the repo isn't as big a deal since I still have to move it into the babel/babel repo.
